// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sheba.Ministry.Infrastructure.Persistence;

#nullable disable

namespace Sheba.Ministry.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MinistryDbContext))]
    [Migration("20260716225021_AddOutboxAndInboxTables")]
    partial class AddOutboxAndInboxTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ministry")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.Ministry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressAr")
                        .HasColumnType("text")
                        .HasColumnName("address_ar");

                    b.Property<string>("AddressEn")
                        .HasColumnType("text")
                        .HasColumnName("address_en");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepthLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("depth_level");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name_en");

                    b.Property<Guid?>("ParentMinistryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_ministry_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ministries_code");

                    b.ToTable("ministries", "ministry");
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryAuthConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HealthCheckPath")
                        .HasColumnType("text")
                        .HasColumnName("health_check_path");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<Guid>("MinistryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ministry_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("retry_count");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId");

                    b.ToTable("ministry_auth_configs", "ministry");
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryAuthCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHeaderName")
                        .HasColumnType("text")
                        .HasColumnName("api_key_header_name");

                    b.Property<string>("ApiKeyPlacementType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("api_key_placement");

                    b.Property<string>("ApiKeyValue")
                        .HasColumnType("text")
                        .HasColumnName("api_key_value");

                    b.Property<Guid>("AuthConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_config_id");

                    b.Property<string>("BasicPassword")
                        .HasColumnType("text")
                        .HasColumnName("basic_password");

                    b.Property<string>("BasicUsername")
                        .HasColumnType("text")
                        .HasColumnName("basic_username");

                    b.Property<string>("BearerToken")
                        .HasColumnType("text")
                        .HasColumnName("bearer_token");

                    b.Property<string>("CachedAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("cached_access_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("OidcClientId")
                        .HasColumnType("text")
                        .HasColumnName("oidc_client_id");

                    b.Property<string>("OidcClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("oidc_client_secret");

                    b.Property<string>("OidcScope")
                        .HasColumnType("text")
                        .HasColumnName("oidc_scope");

                    b.Property<string>("OidcTokenEndpoint")
                        .HasColumnType("text")
                        .HasColumnName("oidc_token_endpoint");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AuthConfigId")
                        .IsUnique();

                    b.ToTable("ministry_auth_credentials", "ministry");
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_config_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("MinistryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ministry_id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name_en");

                    b.Property<string>("PathTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path_template");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_per_minute");

                    b.Property<string>("RequestSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_schema");

                    b.Property<bool>("RequiresCitizenConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_citizen_consent");

                    b.Property<string>("ResponseSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_schema");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("endpoint_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ministry_endpoints_ministry_code");

                    b.ToTable("ministry_endpoints", "ministry");
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<Guid>("MinistryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ministry_id");

                    b.Property<string>("ShebaWebhookPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sheba_webhook_path");

                    b.Property<string>("SigningSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signing_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId");

                    b.ToTable("ministry_webhooks", "ministry");
                });

            modelBuilder.Entity("Sheba.Shared.Kernel.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_messages_event_consumer");

                    b.ToTable("inbox_messages", "ministry");
                });

            modelBuilder.Entity("Sheba.Shared.Kernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_status_next_attempt");

                    b.ToTable("outbox_messages", "ministry");
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryAuthConfig", b =>
                {
                    b.HasOne("Sheba.Ministry.Domain.Entities.Ministry", null)
                        .WithMany("AuthConfigs")
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryAuthCredential", b =>
                {
                    b.HasOne("Sheba.Ministry.Domain.Entities.MinistryAuthConfig", null)
                        .WithOne("Credential")
                        .HasForeignKey("Sheba.Ministry.Domain.Entities.MinistryAuthCredential", "AuthConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryEndpoint", b =>
                {
                    b.HasOne("Sheba.Ministry.Domain.Entities.Ministry", null)
                        .WithMany("Endpoints")
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryWebhook", b =>
                {
                    b.HasOne("Sheba.Ministry.Domain.Entities.Ministry", null)
                        .WithMany("Webhooks")
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.Ministry", b =>
                {
                    b.Navigation("AuthConfigs");

                    b.Navigation("Endpoints");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("Sheba.Ministry.Domain.Entities.MinistryAuthConfig", b =>
                {
                    b.Navigation("Credential");
                });
#pragma warning restore 612, 618
        }
    }
}
